"""Core types for the RAC training loop."""

from dataclasses import dataclass, field
from datetime import date
from typing import Any


@dataclass
class Statute:
    """A statutory provision to encode."""

    citation: str
    text: str
    jurisdiction: str = "us"
    effective_date: date | None = None
    parent: str | None = None
    children: list[str] = field(default_factory=list)


@dataclass
class GeneratedCode:
    """Code generated by the AI."""

    source: str
    citation: str
    iteration: int = 0
    model: str = ""
    prompt_tokens: int = 0
    completion_tokens: int = 0


@dataclass
class TestCase:
    """A test case with inputs and expected outputs."""

    id: str
    inputs: dict[str, Any]
    expected: dict[str, Any]
    description: str = ""


@dataclass
class ExecutionResult:
    """Result of executing code against a test case."""

    case_id: str
    output: dict[str, Any] | None = None
    expected: dict[str, Any] | None = None
    match: bool = False
    error: str | None = None


@dataclass
class Failure:
    """A diagnosed failure from execution."""

    type: str  # "syntax", "runtime", "value_mismatch"
    message: str
    case_id: str | None = None
    expected: Any | None = None
    actual: Any | None = None


@dataclass
class Score:
    """Scoring metrics for generated code."""

    syntax_pass_rate: float = 0.0
    runtime_pass_rate: float = 0.0
    accuracy: float = 0.0
    mean_absolute_error: float = 0.0
    max_error: float = 0.0
    n_cases: int = 0


@dataclass
class IterationRecord:
    """Record of a single training iteration."""

    iteration: int
    code: GeneratedCode
    score: Score
    failures: list[Failure] = field(default_factory=list)


@dataclass
class TrainingResult:
    """Final result of training loop."""

    success: bool
    final_code: GeneratedCode
    iterations: int
    history: list[IterationRecord] = field(default_factory=list)
    remaining_failures: list[Failure] = field(default_factory=list)
